/* Generated By:JavaCC: Do not edit this line. ADQLParserConstants.java */
package FlowSlicer.DataStructure.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ADQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACK = 5;
  /** RegularExpression Id. */
  int RBRACK = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int DOT = 10;
  /** RegularExpression Id. */
  int COLON = 11;
  /** RegularExpression Id. */
  int QUOTE = 12;
  /** RegularExpression Id. */
  int QUESTION = 13;
  /** RegularExpression Id. */
  int FROM = 14;
  /** RegularExpression Id. */
  int TO = 15;
  /** RegularExpression Id. */
  int FLOW = 16;
  /** RegularExpression Id. */
  int KEEP_ACTIVITIES = 17;
  /** RegularExpression Id. */
  int REMOVE_ACTIVITIES = 18;
  /** RegularExpression Id. */
  int KEEP_PERMISSIONS = 19;
  /** RegularExpression Id. */
  int KEEP_LIBRARIES = 20;
  /** RegularExpression Id. */
  int KEEP_SOURCE = 21;
  /** RegularExpression Id. */
  int USES = 22;
  /** RegularExpression Id. */
  int CLASS = 23;
  /** RegularExpression Id. */
  int METHOD = 24;
  /** RegularExpression Id. */
  int STATEMENT = 25;
  /** RegularExpression Id. */
  int STRING_LITERAL = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\":\"",
    "\"\\\'\"",
    "\"?\"",
    "\"FROM\"",
    "\"TO\"",
    "\"FLOW\"",
    "\"KEEPACTIVITIES\"",
    "\"REMOVEACTIVITIES\"",
    "\"KEEPPERMISSIONS\"",
    "\"KEEPLIBRARIES\"",
    "\"KEEPSOURCE\"",
    "\"USES\"",
    "\"Class\"",
    "\"Method\"",
    "\"Statement\"",
    "<STRING_LITERAL>",
  };

}
